### ISSUE TITLE
The table `Search` does not exist in the current database.

### ISSUE THREAD

**Issue by MFYDev** [debridmediamanager/debrid-media-manager#129]
Hi, I am trying to selfhost and got this error when I search

```
The table `Search` does not exist in the current database.
    at In.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6854)
    at In.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/app/node_modules/@prisma/client/runtime/library.js:122:5896)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async PlanetScaleCache.getSearchResults (/app/.next/server/chunks/9432.js:1:3913)
    at async handler (/app/.next/server/pages/api/search/title.js:1:3867) {
  code: 'P2021',
  clientVersion: '5.13.0',
  meta: { modelName: 'Search', table: 'Search' }
}
encountered a search issue PrismaClientKnownRequestError: 
Invalid `prisma.search.findUnique()` invocation:
```

I am using docker compose and here is mine

```yaml
services:
  tor:
    image: debridmediamanager/tor
    container_name: debridmediamanager-tor
    restart: always
    deploy:
      replicas: 1

  web:
    image: debridmediamanager/debrid-media-manager:latest
    container_name: debridmediamanager
    restart: always
    ports:
      - 9898:3000
    env_file:
      - .env
    depends_on:
      - mysql
      - tor
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  
  mysql:
    image: mysql:latest
    container_name: debridmediamanager-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: debridmediamanager
      MYSQL_DATABASE: debridmediamanager
      MYSQL_USER: debridmediamanager
      MYSQL_PASSWORD: debridmediamanager
    volumes:
      - ./mysql:/var/lib/mysql
```
